[phases.build]
cmds = [
  "cd backend && npm install",
  "cd backend && npx prisma generate",
  "cd frontend && npm install", 
  "cd frontend && npm run build"
]

[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']

[start]
cmd = "cd backend && npm start"
