[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']

[phases.build]
cmds = [
  "cd backend && npm install && npx prisma generate && npx tsc",
  "cd frontend && npm install && npm run build"
]

[phases.setup.env]
NIXPACKS_NODE_VERSION = "20"

[start]
cmd = "cd backend && node dist/index.js"
